// src/firebase/config.ts
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY.
import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

let firebaseApp: ReturnType<typeof initializeApp> | null = null;
let firebaseAuth: ReturnType<typeof getAuth> | null = null;
let firebaseDb: ReturnType<typeof getFirestore> | null = null;

function getFirebaseConfig() {
  return {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  };
}

function initializeFirebase() {
  // Only initialize if not already initialized (lazy initialization)
  if (firebaseApp) {
    return { app: firebaseApp, auth: firebaseAuth!, db: firebaseDb! };
  }

  const firebaseConfig = getFirebaseConfig();

  const requiredConfigKeys = [
    'apiKey',
    'authDomain',
    'projectId',
    'storageBucket',
    'messagingSenderId',
    'appId',
  ] as const;

  const missingKeys = requiredConfigKeys.filter((key) => !firebaseConfig[key]);

  if (missingKeys.length) {
    const missingEnvKeys = missingKeys.map((key) =>
      `NEXT_PUBLIC_FIREBASE_${key.replace(/([A-Z])/g, '_$1').toUpperCase()}`
    );
    throw new Error(
      `Missing Firebase configuration. Set ${missingEnvKeys.join(', ')} in .env.local.`
    );
  }

  if (getApps().length) {
    firebaseApp = getApp();
  } else {
    firebaseApp = initializeApp(firebaseConfig);
  }

  firebaseAuth = getAuth(firebaseApp);
  firebaseDb = getFirestore(firebaseApp);

  return { app: firebaseApp, auth: firebaseAuth, db: firebaseDb };
}

// Lazy getters that only initialize when first accessed
export function getFirebaseApp() {
  return initializeFirebase().app;
}

export function getFirebaseAuth() {
  return initializeFirebase().auth;
}

export function getFirebaseDb() {
  return initializeFirebase().db;
}

// For backwards compatibility with existing code
export function getFirebaseInstance() {
  return initializeFirebase();
}
