// src/firebase/config.ts
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY.
import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyCEhJXFd9m9lgoo-Am73Qloosjpa1WyyZY",
  authDomain: "idle-lands-add14.firebaseapp.com",
  databaseURL: "https://idle-lands-add14-default-rtdb.firebaseio.com",
  projectId: "idle-lands-add14",
  storageBucket: "idle-lands-add14.appspot.com",
  messagingSenderId: "721089553497",
  appId: "1:721089553497:web:c89d6a2af0ba0102d2fd48",
  measurementId: "G-6VZLMRJG2N"
};

function initializeFirebase() {
  if (getApps().length) {
    return getApp();
  }
  return initializeApp(firebaseConfig);
}

export const firebaseApp = initializeFirebase();
export const auth = getAuth(firebaseApp);
export const firestore = getFirestore(firebaseApp);
