// src/components/game/GameIcons.tsx
import {
  Trees,
  Disc,
  Wrench,
  Apple,
  GlassWater,
  Cpu,
  Atom,
  Hammer,
  Factory,
  Droplets,
  Radio,
  Power,
  Bot,
  Drill,
  HeartPulse,
  Sandwich,
  CupSoda,
  Battery,
  Search,
  Zap,
  Bed,
  type LucideProps,
  Banana,
  Citrus, // Changed from Lemon
  Grape, // Changed from Beef
  Signal,
  Coins,
  Heart,
  Map,
  Sprout,
  Leaf,
  Layers,
  RectangleHorizontal,
  Package,
  PackageCheck,
  Fuel,
  Carrot,
  Wheat,
  Mountain,
  TestTube,
  Beaker,
  Soup,
  Salad,
  ChefHat,
  Fish,
  HardDrive,
  CircuitBoard,
  Gem,
  Star,
  Building,
  Scroll,
  Pickaxe,
} from 'lucide-react';
import type { Resource, Item } from '@/lib/game-types';

type IconMap = Record<string, React.ReactElement<LucideProps>>;

const iconProps: LucideProps = {
  className: 'inline-block h-4 w-4 mr-1.5 align-middle text-muted-foreground',
};

export const resourceIcons: Record<Resource, React.ReactElement<LucideProps>> = {
  wood: <Trees {...iconProps} />,
  stone: <Disc {...iconProps} />,
  scrap: <Wrench {...iconProps} />,
  apple: <Apple {...iconProps} />,
  water: <GlassWater {...iconProps} />,
  components: <Cpu {...iconProps} />,
  uranium: <Atom {...iconProps} />,
  lemon: <Citrus {...iconProps} />,
  banana: <Banana {...iconProps} />,
  peach: <Grape {...iconProps} />,
  appleSeeds: <Sprout {...iconProps} />,
  carrot: <Carrot {...iconProps} />,
  carrotSeeds: <Sprout {...iconProps} />,
  corn: <Wheat {...iconProps} />,
  cornSeeds: <Sprout {...iconProps} />,
  silver: <Coins {...iconProps} className="text-yellow-500" />,
  mutatedTwigs: <Leaf {...iconProps} />,
  ironIngot: <Layers {...iconProps} />,
  biomass: <Leaf {...iconProps} color="green" />,
  charcoal: <Fuel {...iconProps} />,
  sand: <Mountain {...iconProps} />,
  glassTube: <TestTube {...iconProps} />,
  glassJar: <Beaker {...iconProps} />,
  pickledPeaches: <Package {...iconProps} />,
  oldBoot: <Package {...iconProps} />,
  goldenBass: <Fish {...iconProps} />,
  reactorCoreShard: <Atom {...iconProps} />,
  goldenGlowfish: <Fish {...iconProps} />,
  bunkerCarp: <Fish {...iconProps} />,
  caveEel: <Fish {...iconProps} />,
  armoredFish: <Fish {...iconProps} />,
  militaryRation: <Package {...iconProps} />,
  waterloggedDataChip: <HardDrive {...iconProps} />,
  goldenEel: <Fish {...iconProps} />,
  preWarTech: <CircuitBoard {...iconProps} />,
  acidSwimmer: <Fish {...iconProps} />,
  toxicTrout: <Fish {...iconProps} />,
  chemicalCarp: <Fish {...iconProps} />,
  strangeCrystal: <Gem {...iconProps} />,
  chemicalSample: <TestTube {...iconProps} />,
  goldenSwimmer: <Fish {...iconProps} />,
  experimentalCompound: <TestTube {...iconProps} />,
  craterDweller: <Fish {...iconProps} />,
  depthFish: <Fish {...iconProps} />,
  meteorFragment: <Star {...iconProps} />,
  cosmicDebris: <Star {...iconProps} />,
  goldenCraterFish: <Fish {...iconProps} />,
  meteoriteShard: <Star {...iconProps} />,
  ancientArtifact: <Scroll {...iconProps} />,
  urbanScavengerFish: <Fish {...iconProps} />,
  rubbleSwimmer: <Fish {...iconProps} />,
  buildingMaterial: <Building {...iconProps} />,
  preWarCurrency: <Coins {...iconProps} />,
  glassShard: <Gem {...iconProps} />,
  goldenCityFish: <Fish {...iconProps} />,
  pristinePreWarItem: <Package {...iconProps} />,
  treasureCache: <Package {...iconProps} />,
  cookedFish: <Fish {...iconProps} />,
  cornChowder: <Soup {...iconProps} />,
  vegetableMedley: <Salad {...iconProps} />,
  fruitSalad: <Salad {...iconProps} />,
  lemonade: <GlassWater {...iconProps} />,
  cookedApple: <Apple {...iconProps} />,
  kitchen: <ChefHat {...iconProps} />,
  iron: <Pickaxe {...iconProps} />,
  rawFish: <Fish {...iconProps} />,
  rawSalmon: <Fish {...iconProps} />,
  rawTuna: <Fish {...iconProps} />,
  rawShark: <Fish {...iconProps} />,
  mutantMinnow: <Fish {...iconProps} />,
  radPerch: <Fish {...iconProps} />,
  mutantCatfish: <Fish {...iconProps} />,
  glowfish: <Fish {...iconProps} />,
  rustyCan: <Package {...iconProps} />,
  glowingAlgae: <Leaf {...iconProps} />,
  goldenMinnow: <Fish {...iconProps} />,
  sludgeBass: <Fish {...iconProps} />,
  irradiatedCarp: <Fish {...iconProps} />,
  bioLuminescentMoss: <Leaf {...iconProps} />,
};

export const itemIcons: Record<Item, React.ReactElement<LucideProps>> = {
  stoneAxe: <Hammer {...iconProps} />,
  metalDetector: <Signal {...iconProps} />,
  workbench: <Factory {...iconProps} />,
  waterPurifier: <Droplets {...iconProps} />,
  furnace: <Power {...iconProps} />,
  radio: <Radio {...iconProps} />,
  generator: <Power {...iconProps} />,
  droneBay: <Bot {...iconProps} />,
  hydroponicsBay: <Sprout {...iconProps} />,
  miningRig: <Drill {...iconProps} />,
  cookedApple: <Zap {...iconProps} />,
  crudeMap: <Map {...iconProps} />,
  ironPlates: <RectangleHorizontal {...iconProps} />,
  biomassCompressor: <Package {...iconProps} />,
  pickaxe: <Pickaxe {...iconProps} />,
};

export const statIcons = {
    health: <Heart {...iconProps} />,
    hunger: <Sandwich {...iconProps} />,
    thirst: <CupSoda {...iconProps} />,
    energy: <Battery {...iconProps} />,
}

export const allIcons: IconMap = { ...resourceIcons, ...itemIcons };
