// src/lib/game-data/initial-state.ts
import type { GameState, Statistics, LocationId } from '@/lib/game-types';
import { xpCurve } from './xp-curve';

const emptyInventory = {
  wood: 0,
  stone: 0,
  scrap: 0,
  apple: 0,
  water: 0,
  components: 0,
  uranium: 0,
  lemon: 0,
  banana: 0,
  peach: 0,
  appleSeeds: 0,
  carrot: 0,
  carrotSeeds: 0,
  corn: 0,
  cornSeeds: 0,
  silver: 0,
  mutatedTwigs: 0,
  ironIngot: 0,
  biomass: 0,
  charcoal: 0,
  sand: 0,
  glassTube: 0,
  glassJar: 0,
  pickledPeaches: 0,
  iron: 0,
  rawFish: 0,
  rawSalmon: 0,
  rawTuna: 0,
  rawShark: 0,
  mutantMinnow: 0,
  radPerch: 0,
  mutantCatfish: 0,
  glowfish: 0,
  rustyCan: 0,
  glowingAlgae: 0,
  goldenMinnow: 0,
  sludgeBass: 0,
  irradiatedCarp: 0,
  bioLuminescentMoss: 0,
  oldBoot: 0,
  goldenBass: 0,
  reactorCoreShard: 0,
  goldenGlowfish: 0,
  bunkerCarp: 0,
  caveEel: 0,
  armoredFish: 0,
  militaryRation: 0,
  waterloggedDataChip: 0,
  goldenEel: 0,
  preWarTech: 0,
  acidSwimmer: 0,
  toxicTrout: 0,
  chemicalCarp: 0,
  strangeCrystal: 0,
  chemicalSample: 0,
  goldenSwimmer: 0,
  experimentalCompound: 0,
  craterDweller: 0,
  depthFish: 0,
  meteorFragment: 0,
  cosmicDebris: 0,
  goldenCraterFish: 0,
  meteoriteShard: 0,
  ancientArtifact: 0,
  urbanScavengerFish: 0,
  rubbleSwimmer: 0,
  buildingMaterial: 0,
  preWarCurrency: 0,
  glassShard: 0,
  goldenCityFish: 0,
  pristinePreWarItem: 0,
  treasureCache: 0,
  stoneAxe: 0,
  metalDetector: 0,
  workbench: 0,
  waterPurifier: 0,
  furnace: 0,
  radio: 0,
  generator: 0,
  droneBay: 0,
  hydroponicsBay: 0,
  miningRig: 0,
  cookedApple: 0,
  crudeMap: 0,
  ironPlates: 0,
  biomassCompressor: 0,
  pickaxe: 0,
};

export const initialStatistics: Statistics = {
  timesExplored: 0,
  timesScavenged: 0,
  timesFished: 0,
  timesMined: 0,
  deaths: 0,
  totalItemsGained: {
    ...emptyInventory
  },
  itemsCrafted: {},
};


export const initialState: GameState = {
  characterName: 'Survivor',
  level: 1,
  xp: 0,
  xpToNextLevel: xpCurve[0],
  upgradePoints: 0,
  playerStats: {
    health: 100,
    hunger: 100,
    thirst: 100,
    energy: 100,
  },
  inventory: {
    ...emptyInventory,
    apple: 5,
    water: 5,
    silver: 20,
  },
  equipment: {
    hand: null,
    body: null,
  },
  statistics: initialStatistics,
  log: [
    {
      id: 1,
      text: 'You awaken to the grey light of a sunless sky. The world you knew is gone, replaced by ruins and silence.',
      timestamp: Date.now(),
      type: 'event' as const,
    },

    {
      id: 2,
      text: 'Survival is your only goal. Find resources, craft tools, and endure.',
      timestamp: Date.now() + 1,
      type: 'info' as const,
    },
  ],
  currentLocation: 'outskirts',
  unlockedRecipes: ['recipe_stoneAxe', 'recipe_crudeMap', 'recipe_grindStone'],
  builtStructures: [],
  unlockedFlags: [],
  unlockedLocations: ['outskirts'],
  unlockedTech: [],
  lockedItems: [],
  completedQuests: [],
  storageLevel: 0,
  energyLevel: 0,
  hungerLevel: 0,
  thirstLevel: 0,
  healthLevel: 0,
  droneLevel: 0,
  farmPlotLevel: 0,
  machineSlotLevel: 0,
  automationSpeedLevel: 0,
  explorationEfficiencyLevel: 0,
  hasFishingLuck: false,
  restEfficiencyLevel: 0,
  isInitialized: false,
  gameTick: 0,
  isResting: false,
  isIdle: false,
  smeltingQueue: 0,
  ironIngotSmeltingQueue: 0,
  charcoalSmeltingQueue: 0,
  glassSmeltingQueue: 0,
  droneIsActive: false,
  droneReturnTimestamp: null,
  droneMissionQueue: 0,
  droneMissionType: null,
  power: 0,
  powerDrainCounter: 0,
  theme: 'dark',
  lastSavedTimestamp: Date.now(),
  lastDailyRewardClaimed: 0,
  farmPlots: [],
  masteryClaimed: {},
  machines: [],
  powerCapacity: 0,
  powerConsumption: 0,
  skills: {},
  npcReputation: {},
  unlockedLore: [],
  currentFishingZone: 'toxic_puddle',
  caughtFish: {},
  smeltingTimestamps: {
    components: null,
    iron: null,
    charcoal: null,
    glass: null,
  },
};
